export const REQUEST_EMAIL_PASS_CHECK = 'REQUEST_EMAIL_PASS_CHECK'

export const REQUEST_LOGGED_IN_USER_PROFILE = 'REQUEST_LOGGED_IN_USER_PROFILE'

export const REQUEST_BESTSELLER_LIST = 'REQUEST_BEST_SELLER_LIST'

export const REQUEST_COMMUNITY_MAIN_BOARD_LIST = 'REQUEST_COMMUNITY_MAIN_BOARD_LIST'

export const REQUEST_BOARD_TO_READ = 'REQUEST_BOARD_TO_READ'

export const REQUEST_SEARCH_BOARD_WITH_TITLE_AND_KEYWORD = 'REQUEST_SEARCH_BOARD_WITH_TITLE_AND_KEYWORD'