export const REQUEST_EMAIL_PASS_CHECK = 'REQUEST_EMAIL_PASS_CHECK'

export const REQUEST_LOGGED_IN_USER_PROFILE = 'REQUEST_LOGGED_IN_USER_PROFILE'

export const REQUEST_BESTSELLER_LIST = 'REQUEST_BEST_SELLER_LIST'