export const REQUEST_DIARY_BOARD_LIST_FROM_SPRING = 'REQUEST_DIARY_BOARD_LIST_FROM_SPRING'
export const REQUEST_DIARY_BOARD_FROM_SPRING = 'REQUEST_DIARY_BOARD_FROM_SPRING'

export const REQUEST_LOGIN_USER_FROM_SPRING = 'REQUEST_LOGIN_USER_FROM_SPRING'

export const IS_AUTHENTICATED = 'IS_AUTHENTICATED'
export const USER_LOGIN_CHECK = 'USER_LOGIN_CHECK'

export const THUMB_STATUS_COUNT = 'THUMB_STATUS_COUNT'

export const REQUEST_COMMENT_LIST_FROM_SPRING = 'REQUEST_COMMENT_LIST_FROM_SPRING'

export const VIDEOS = 'VIDEOS'
export const MY_SAVE_VIDEOS_LIST = 'MY_SAVE_VIDEOS_LIST'



