export const REQUEST_DIARY_BOARD_LIST_FROM_SPRING = 'REQUEST_DIARY_BOARD_LIST_FROM_SPRING'
export const REQUEST_DIARY_BOARD_FROM_SPRING = 'REQUEST_DIARY_BOARD_FROM_SPRING'

export const REQUEST_LOGIN_USER_FROM_SPRING = 'REQUEST_LOGIN_USER_FROM_SPRING'

export const IS_AUTHENTICATED = 'IS_AUTHENTICATED'
export const USER_LOGIN_CHECK = 'USER_LOGIN_CHECK'
