export const REQUEST_LOGIN_USER_FROM_SPRING = 'REQUEST_LOGIN_USER_FROM_SPRING'
export const REQUEST_LOGIN_USER_NICKNAME_FROM_SPRING = 'REQUEST_LOGIN_USER_NICKNAME_FROM_SPRING'

export const IS_AUTHENTICATED = 'IS_AUTHENTICATED'
export const USER_LOGIN_CHECK = 'USER_LOGIN_CHECK'

export const REQUEST_LEND_LIST_FROM_SPRING = 'REQUEST_LEND_LIST_FROM_SPRING'
export const REQUEST_LEND_FROM_SPRING = 'REQUEST_LEND_FROM_SPRING'

export const REQUEST_COMMUNITY_LIST_FROM_SPRING = 'REQUEST_COMMUNITY_LIST_FROM_SPRING'
export const REQUEST_COMMUNITY_FROM_SPRING = 'REQUEST_COMMUNITY_FROM_SPRING'

export const REQUEST_REVIEW_LIST_FROM_SPRING = 'REQUEST_REVIEW_LIST_FROM_SPRING'
export const REQUEST_REVIEW_FROM_SPRING = 'REQUEST_REVIEW_FROM_SPRING'



