export const CHECK_DUPLICATE_EMAIL_TO_SPRING = 'CHECK_DUPLICATE_EMAIL_TO_SPRING';
export const REQUEST_CURRENT_USER_NICKNAME_FROM_SPRING = 'REQUEST_CURRENT_USER_NICKNAME_FROM_SPRING';
export const CHECK_DUPLICATE_NICKNAME_TO_SPRING = 'CHECK_DUPLICATE_NICKNAME_TO_SPRING';
// export const REQUEST_LOGIN_STATE_TO_SPRING = 'REQUEST_LOGIN_STATE_TO_SPRING'